### PR TITLE
Fix panics on invalid sized trace & span IDs

### PR DESCRIPTION
**Pull request by kevinnoel-be**
Fix for https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33566

### CODE REVIEW

**Review by mx-psi — COMMENTED** [review]
Thanks for the PR, it seems like there are some tests failing: https://github.com/DataDog/opentelemetry-mapping-go/actions/runs/9515937620/job/26238071289?pr=340#step:6:62 would you be able to take a look at those?

**Comment by kevinnoel-be** [comment]
> Thanks for the PR, it seems like there are some tests failing: https://github.com/DataDog/opentelemetry-mapping-go/actions/runs/9515937620/job/26238071289?pr=340#step:6:62 would you be able to take a look at those?

Oops, sure I'll check that further on my side. Sorry for the noise 😅

**Comment by kevinnoel-be** [comment]
Should be better now, this is how [some upstream process parses it](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/883801950f337e9157955c6a089e116b4ef5657f/pkg/ottl/contexts/internal/ids.go#L18).

**Review by mx-psi — APPROVED** [review]
Thanks!

**Pull request merged**
